
services:
  scheduler:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - /opt/slskd/downloads:/downloads
    environment:
      - SLSKD_BASE=http://192.168.1.7:5030
      - SLSKD_API_KEY=OXMRJ43VWQU71F9L68TZYHNP
    restart: unless-stopped
