version: "3.9"

services:
  slsk_scheduler:
    image: ghcr.io/tommypopescu/slskd_sldl_scheduler:latest
    pull_policy: always
    user: "10001:100"
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - /opt/slskd/downloads:/downloads    # folderul slskd de pe host
    restart: unless-stopped