name: Build and Push (GHCR)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile          # <-- important: în rădăcină
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dir-cleaner:latest
            ghcr.io/${{ github.repository_owner }}/dir-cleaner:${{ github.sha }}
